version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - type: bind
        source: ./mosquitto/conf
        target: /mosquitto/config

